spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
  jpa:
    open-in-view: false
  redis:
    port: 6379
    host: 127.0.0.1




mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名下划线自动转换
